// What Rust's `format!("{}", x)` writes for a fixed list of `f64` and `f32` values -- the oracle the
// plain rendering of a float in sysl (`print`, `str`, a bare interpolation hole, `Display`) is held to.
//
// It prints a whole sysl `@tests` file on standard output; the committed copy is
// `library/sysl/display_oracle_tests.sysl`. Regenerate it with
//
//     rustc -O -o <scratch>/oracle scripts/float_display_oracle.rs
//     <scratch>/oracle > library/sysl/display_oracle_tests.sysl
//
// The list is fixed and the random part is a seeded xorshift, so a regeneration under the same Rust
// writes the same file.

struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.0 = x;
        x
    }
}

fn f64_values() -> Vec<f64> {
    let mut v: Vec<f64> = vec![
        0.0, -0.0, f64::INFINITY, f64::NEG_INFINITY, f64::NAN, -f64::NAN,
        1.0, -1.0, 0.1, 0.2, 0.3, 0.1 + 0.2, 1.0 / 3.0, 2.0 / 3.0, 1.5, -2.5, 100.0, 1e20, 1e-7,
        1e15, 1e16, 1e17, 1e21, 1e22, 1e23, 123456789012345680.0, 9007199254740992.0,
        9007199254740993.0, 18446744073709551616.0, 9223372036854775808.0, f64::MAX, f64::MIN,
        f64::MIN_POSITIVE, f64::EPSILON, std::f64::consts::PI, std::f64::consts::E,
        f64::from_bits(1), f64::from_bits(2), f64::from_bits(3), f64::from_bits(0x000fffffffffffff),
        f64::from_bits(0x0010000000000001), 5e-324, 1e-323, 2.2250738585072014e-308,
        0.000001, 0.00001, 0.0001, 0.001, 123.456, -0.000123, 299792458.0, 6.02214076e23,
        6.62607015e-34, 1.7976931348623157e308, 4.9406564584124654e-324, 0.5, 0.25, 0.125, 0.0625,
        2.0f64.powi(-24), 2.0f64.powi(-1022), 2.0f64.powi(-1023), 2.0f64.powi(1023), 1e-5, 1.0e-4,
        5.0e-5, 9.5367431640625e-7, 0.3333333333333333, 4.35, 2.675, 1.005, 1e300, 1e-300,
        1234567890123456789.0, 0.000000000000000000001, 2.5e-8, 7.0e-10, 3.0e10,
    ];
    let mut k = -1074;
    while k <= 1023 {
        v.push(2.0f64.powi(k));
        k += 37;
    }
    let mut e = -323;
    while e <= 308 {
        let x: f64 = format!("1e{}", e).parse().unwrap();
        v.push(x);
        v.push(f64::from_bits(x.to_bits() + 1));
        v.push(f64::from_bits(x.to_bits() - 1));
        e += 23;
    }
    for i in 1..20 {
        v.push(i as f64 + 0.5);
        v.push((i as f64) * 0.1);
    }
    let mut r = Rng(0x9e3779b97f4a7c15);
    let mut n = 0;
    while n < 150 {
        let x = f64::from_bits(r.next());
        if x.is_finite() {
            v.push(x);
            n += 1;
        }
    }
    // Ordinary magnitudes, where most real numbers a program prints live.
    for _ in 0..150 {
        let m = (r.next() >> 11) as f64 / (1u64 << 53) as f64;
        let e = (r.next() % 40) as i32 - 20;
        v.push(m * 10f64.powi(e));
    }
    v
}

fn f32_values() -> Vec<f32> {
    let mut v: Vec<f32> = vec![
        0.0, -0.0, f32::INFINITY, f32::NEG_INFINITY, f32::NAN, -f32::NAN,
        1.0, -1.0, 0.1, 0.2, 0.3, 1.0 / 3.0, 2.0 / 3.0, 1.5, -2.5, 100.0, 1e20, 1e-7, 16777216.0,
        16777217.0, 1e10, 1e30, f32::MAX, f32::MIN, f32::MIN_POSITIVE, f32::EPSILON,
        std::f32::consts::PI, std::f32::consts::E, f32::from_bits(1), f32::from_bits(2),
        f32::from_bits(0x007fffff), f32::from_bits(0x00800001), 0.000001, 123.456, 3.4028235e38,
        1.4e-45, 7.0e-46, 0.5, 0.125, 1e-5, 2.0f32.powi(-24), 299792458.0, 4.35, 1.005,
    ];
    let mut k = -149;
    while k <= 127 {
        v.push(2.0f32.powi(k));
        k += 11;
    }
    let mut e = -45;
    while e <= 38 {
        let x: f32 = format!("1e{}", e).parse().unwrap();
        v.push(x);
        if x.to_bits() > 1 {
            v.push(f32::from_bits(x.to_bits() - 1));
        }
        v.push(f32::from_bits(x.to_bits() + 1));
        e += 7;
    }
    let mut r = Rng(0x2545f4914f6cdd1d);
    let mut n = 0;
    while n < 150 {
        let x = f32::from_bits((r.next() >> 32) as u32);
        if x.is_finite() {
            v.push(x);
            n += 1;
        }
    }
    for _ in 0..150 {
        let m = (r.next() >> 40) as f32 / (1u32 << 24) as f32;
        let e = (r.next() % 20) as i32 - 10;
        v.push(m * 10f32.powi(e));
    }
    v
}

fn main() {
    println!("module sysl");
    println!("@tests");
    println!();
    println!("// GENERATED by scripts/float_display_oracle.rs -- do not edit by hand. Every expected string is");
    println!("// what Rust's `format!(\"{{}}\", x)` writes for the same bits at the same width: the shortest digits");
    println!("// that read back at that width, written out positionally, with no exponent and no trailing `.0`.");
    println!();
    println!("private rust64(bits: u64, want: string) = assert_eq(str(real.from_bits(bits)), want)");
    println!();
    println!("private rust32(bits: u32, want: string) = assert_eq(str(f32.from_bits(bits)), want)");

    let a = f64_values();
    for (i, chunk) in a.chunks(60).enumerate() {
        println!();
        println!("@test(\"a real renders as Rust's Display renders it, part {}\")", i + 1);
        println!("fdr_real_{}()", i + 1);
        for x in chunk {
            println!("    rust64(0x{:016x}, \"{}\")", x.to_bits(), x);
        }
        println!("end fdr_real_{}", i + 1);
    }
    let b = f32_values();
    for (i, chunk) in b.chunks(60).enumerate() {
        println!();
        println!("@test(\"an f32 renders as Rust's Display renders it, part {}\")", i + 1);
        println!("fdr_f32_{}()", i + 1);
        for x in chunk {
            println!("    rust32(0x{:08x}, \"{}\")", x.to_bits(), x);
        }
        println!("end fdr_f32_{}", i + 1);
    }
}
