package sh.sysl

/** The C header for whatever a module `@export`ed (`15 §12`).
 *
 * **It is a translation of one signature at a time and nothing more.** `ExportCheck` has already
 * held every exported function to a signature C can spell, so there is no type here that needs a
 * decision — each one has exactly one C spelling and this writes it down. That is the whole reason
 * the header is the last of the three pieces and the cheapest: the marking is what does the work,
 * and a header is what the marking makes mechanical.
 *
 * **`<stdint.h>` and `<stdbool.h>` rather than `int` and `long`.** C's own integer names say what a
 * type is *at least*, and sysl's say what it *is* — an `i32` is thirty-two bits everywhere, and
 * writing it `int` would be right on every machine anyone is likely to use and wrong as a claim.
 * The fixed-width names mean what sysl means, so the header states the actual contract.
 */
object CHeader {

  /** The header for a compiled module: a guard, the two includes, and one prototype per export in
   * the order the functions were declared.
   *
   * `name` is what the include guard is built from — the project's name, so two headers in one C
   * project do not collide. Anything not a C identifier is replaced, since a guard is a macro name
   * and a project may be called what it likes.
   */
  def render(funcs: List[TFunc], name: String): String = {
    val exports = funcs.filter(_.exported.isDefined).sortBy(_.exported.get)
    val guard   = s"SYSL_${name.map(c => if c.isLetterOrDigit then c.toUpper else '_')}_H"
    val out     = new StringBuilder

    out ++= s"/* Generated by sysl. The declarations a C project needs to call into this module. */\n"
    out ++= s"#ifndef $guard\n#define $guard\n\n"
    out ++= "#include <stdbool.h>\n#include <stdint.h>\n#include <stddef.h>\n\n"
    out ++= "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n"

    if exports.isEmpty then
      // A header with nothing in it is worth writing rather than refusing: a build that exported
      // nothing is a build whose author forgot the attribute, and an empty header says so where a
      // missing file would read as a step that had not run.
      out ++= "/* This module exports nothing — no function in it is marked '@export'. */\n\n"
    else for f <- exports do out ++= s"${prototype(f)};\n"

    if exports.nonEmpty then out ++= "\n"

    out ++= "#ifdef __cplusplus\n}\n#endif\n\n"
    out ++= s"#endif /* $guard */\n"
    out.toString
  }

  /** One function, as C declares it. A parameter keeps the name sysl gave it — a prototype's names
   * are documentation and nothing else, and the reader is better served by `count` than by nothing.
   */
  def prototype(f: TFunc): String = {
    val params =
      if f.params.isEmpty then "void"
      else f.params.map((n, t) => s"${spell(t)} $n").mkString(", ")

    s"${spell(f.retTy)} ${f.exported.get}($params)"
  }

  /** A sysl type as C spells it.
   *
   * Only the types `ExportCheck.crosses` admits reach here, so the fallthrough is unreachable rather
   * than a default — and it is written as a refusal in the text it produces, because a header that
   * quietly emitted `void*` for something it did not understand would compile on both sides and be
   * wrong in between.
   */
  def spell(t: Type): String = Type.repr(t) match
    case Type.Unit | Type.Never              => "void"
    case Type.Bool                           => "bool"
    // A `char` is a Unicode scalar value, which is four bytes and not C's `char`. `uint32_t` is what
    // it is; C's own name for that idea is `char32_t`, which needs a header C99 does not have.
    case Type.Char                           => "uint32_t"
    case Type.Integer(bits, signed, _)       => s"${if signed then "" else "u"}int${bits}_t"
    case Type.Floating(32)                   => "float"
    case Type.Floating(_)                    => "double"
    // Pointed-to `void` has no size in C, so a pointer to nothing is `void *` and everything else
    // keeps its pointee. A pointer to a type C cannot spell never gets here.
    case Type.Ptr(Type.Unit)                 => "void *"
    case Type.Ptr(inner)                     => s"${spell(inner)} *"
    case Type.CFn(params, ret)               =>
      val ps = if params.isEmpty then "void" else params.map(spell).mkString(", ")
      s"${spell(ret)} (*)($ps)"
    case other                               => s"/* no C spelling for ${other} */ void"
}
